[qr]
#промежуток в котором генерируется случайное число для requestId
idMax=999
#префикс для requestId для возможноти горизонтального масштабирования
idPrefix=9
#название лого файла тображаемого в центре qr кода
logoPath="logo.png"
#цвет в центре qr кода
colorCenter="05ffb8"
#цвет края qr кода
colorEdge="007aff"
#радиус одного бита qr кода
pixRadius=5
#промежуток времени через который qr код можно повторно использовать
lifetime=120
#размер буфера подготовленных qr кодов
sizeBuffer=8
#колличество потоков подготавливающих qr коды
numberOfThreads=1
#шаблон по которому создается qr код
template="{\"id\": %d}"